// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWP391.Repositories.Models;

public partial class Campus
{
    public int Id { get; set; }

    public string CampusCode { get; set; }

    public string CampusName { get; set; }

    public virtual ICollection<Location> Locations { get; set; } = new List<Location>();
}