// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWP391.Repositories.Models;

public partial class Category
{
    public int Id { get; set; }

    public string CategoryCode { get; set; }

    public string CategoryName { get; set; }

    public int DepartmentId { get; set; }

    public int? SlaResolveHours { get; set; }

    public string Status { get; set; }

    public virtual Department Department { get; set; }

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}