// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWP391.Repositories.Models;

public partial class Location
{
    public int Id { get; set; }

    public string LocationCode { get; set; }

    public string LocationName { get; set; }

    public int CampusId { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Campus Campus { get; set; }

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}