// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWP391.Repositories.Models;

public partial class Ticket
{
    public int Id { get; set; }

    public string TicketCode { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string ImageUrl { get; set; }

    public int RequesterId { get; set; }

    public int? AssignedTo { get; set; }

    public int? ManagedBy { get; set; }

    public int LocationId { get; set; }

    public int CategoryId { get; set; }

    public string Status { get; set; }

    public string ContactPhone { get; set; }

    public string Note { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? ResolveDeadline { get; set; }

    public DateTime? ResolvedAt { get; set; }

    public DateTime? ClosedAt { get; set; }

    public int? RatingStars { get; set; }

    public string RatingComment { get; set; }

    public virtual User AssignedToNavigation { get; set; }

    public virtual Category Category { get; set; }

    public virtual Location Location { get; set; }

    public virtual User ManagedByNavigation { get; set; }

    public virtual User Requester { get; set; }
}