// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWP391.Repositories.Models;

public partial class User
{
    public int Id { get; set; }

    public string UserCode { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string PasswordHash { get; set; }

    public string PhoneNumber { get; set; }

    public int RoleId { get; set; }

    public int? DepartmentId { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Department Department { get; set; }

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    public virtual Role Role { get; set; }

    public virtual ICollection<Ticket> TicketAssignedToNavigations { get; set; } = new List<Ticket>();

    public virtual ICollection<Ticket> TicketManagedByNavigations { get; set; } = new List<Ticket>();

    public virtual ICollection<Ticket> TicketRequesters { get; set; } = new List<Ticket>();
}